version: "3"

services:
  dufs:
    image: docker.io/sigoden/dufs:latest
    networks:
      - backend
    command:
      - "/data"
    volumes:
      - ${PWD}/tests/data/http-scrape/:/data
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    networks:
      - backend
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "http-scrape-integration-tests"
      - "--lib"
      - "sources::http_scrape::scrape::integration_tests::"
    depends_on:
      - dufs
    volumes:
      - ${PWD}:/code
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  backend: {}

volumes:
  cargogit: {}
  cargoregistry: {}
